var affirmation = ['You gotta be insane to out sane the sane',
"it's times like this where you got to put your behind in the past",
'The past can hurt, but you can decide to run or learn from it',
'laugh in the face of danger',
"when life gives you lemons, squeeze em back into life's eyes",
'remember who you are',
'Constipation? More like over flowing inspiration!',
"Those who do not respect you don't deserve your time",
"you're only in trouble if you get caught",
"you're only a fool if you give up",
'if stupidity got you into this mess, it can get you out',
"if you don't like your job, just go in everyday and do it hall-assed",
"The world is a cruel yet beautiful place",
"sucking at something is a step closer to being good at that something",
"No matter how deep the night, it will turn to day eventually",
"Sometimes it's necessary to do unnecessary things",
"If you win, you live. If you lose, you die. If you don’t fight, you can’t win",
"If you don’t like your destiny, don’t accept it. Instead, have the courage to change it the way you want it to be",
"Whatever you lose, you’ll find it again. But what you throw away you’ll never get back",
"All we can do is live until the day we die. Control what we can…and fly free.",
"leave tomorrow's problems for tomorrow you",
"Hardwork betrays no one",
"Being alone is better than being with the wrong person",
"Who decides limits?",
"Living has it own challenges. I’ll give you just one piece of advice. Don’t quit",
"it's ok to be sad",
"Being weak is nothing to be ashamed of… Staying weak is",
"Whether you win or lose… You can always come out ahead by learning from the experience",
"You can die anytime, but living takes true courage",
"A person can change, at the moment when the person wishes to change",
"Mistakes are not shackles that halt one from stepping forward. Rather, they are that which sustain and grow one’s heart.",
"Whatever you do, enjoy it to the fullest. That is the secret of life",
"You can’t win a game by doing nothing. And if someone else wins it for you then you haven’t accomplished anything",
"It takes an Idiot do something cool, that’s why it is cool.",
"We can’t waste time worrying about the what if’s",
"You need to accept the fact that you’re not the best and have all the will to strive to be better than anyone you face",
"What you can’t accomplish alone, becomes doable when you’re with someone else",
"A skyscraper built within your mind will never fall down",
"Push through the pain, giving up hurts more",
"We need to stop living for others. From now on…Let’s live for ourselves!",
"No matter how messed up things get, you can always figure out the best solution",
"Endure it. Don’t let go",
"Believe in your own power",
"If we were normal, we might not be alive today. And that, my friend, is what gives us the edge we need",
"If you wanna make people dream, you’ve gotta start by believing in that dream yourself",
"You’re not a good for nothing person. I think that being able to try your hardest to be something is a talent by itself",
"Don’t worry about what other people think. Hold your head up high and plunge forward",
"can’t find a door? Make your own",
"why do you think your eyes are placed in front? That is for you to see what’s up ahead",
"Even if no one believes in you, stick out your best and scream your defiance",
"You’ll stumble many times in the future, but when you do, each time you’ll have more strength to bounce back",
"You have to accept life as it is. Acceptance is the key for surviving the worst situations",
"Yesterday is history, tomorrow is a mystery, but today is a gift. That is why it is called the present",
"No matter what you do, that seed will grow to be a peach tree. You may wish for an apple or an orange, but you will get a peach",
"an acorn can only become the mighty oak, not a cherry tree. You must let her grow into what she will be",
"Believe in me that believes in you",
"Remember, licking doorknobs is illegal on other planets",
"Who's gonna stop you? Mister McDoesn'tExist?",
"Believe in the heart of the cards",
]

var mantra = ['just keep swimming',
'inner peace',
'poyo',
'potato potwatwa',
'Do you know the muffin man?',
'There are no accidents',
'nothing is impossible',
'Time is an illusion, there is only the now.',
'fuck inner peace',
'nothing but shadows',
'REEEEEEE',
"If I was a mom…this would be kind of shocking. Just call me daddy!",
"I’m ugly and I’m proud!",
"Is mayonnaise an instrument?",
"Every villian is lemon",
"Wait, we’re not cavemen. We have technology.",
"Did you smell it? That smell. A kind of smelly smell. The smelly smell that smells…smelly.",
"Well, it may be stupid, but it’s also dumb.",
"In carnage i bloom",
"The Krusty Krab pizza is the pizza for you and me",
"Another day, another migraine",
"Ravioli ravioli. Give me the formuoli.",
"waaaaahhh~",
"Round-house",
"I didn't fall. I attacked the floor",
"Oh well",
"It is what it is",
"VIVA LA LOCA",
"Meow meow meow",
"Easy peezy lemon squeezy",
"Another day another dollar",
"This too shall pass",
"scooby-doop pee-doop",
"HOLD THE DOOR",
"Everything is awesome. Everything is cool when you're part of the team!",
"leedle leedle leee",
"Just do it!",
]
